Features/delivery page
frizhub-repo/rc-chinese-rest pull request #7
Opened 2021-08-03 16:05 UTC by Dawood-Javed

2021-08-04 08:04 UTC, haroonzafarFrizhub approved these changes

2021-08-09 06:25 UTC, Atif252 requested changes
Code is not properly formatted

2021-08-09 06:27 UTC, Atif252 requested changes

2021-08-09 06:27 UTC, Atif252 commented on src/components/Menu/Hero.js
> +      console.log({ res });
Remove console.log

2021-08-09 09:40 UTC, haroonzafarFrizhub commented on src/components/Menu/menuStyles.css
> +}
End of Line.

2021-08-09 09:40 UTC, haroonzafarFrizhub commented on public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favico.ico" />
Rename the file correctly.

2021-08-10 06:39 UTC, haroonzafarFrizhub approved these changes

2021-08-10 06:43 UTC, merged